### ISSUE TITLE
Multiline Comments

### ISSUE THREAD

**Issue by dorian3343** [nevalang/neva#634]
Title is self explanatory, we're missing multi line comments.

Example

```
/*
 . . . 
*/
```

**Comment by emil14** [comment]
Honestly I intentionally didn't add it because I failed to see why need it. I personally never use this.

There's a shortcut for `//` in any IDE which isn't the case for multi-line comment. Also bunch of one-liners can do the same thing. E.g. I think I almost never see multi-line comments in Go, even tho sometimes comment sections are very big.

Could you please describe your opinion on this? What is the use case for multiple-comment? What it adds that's impossible with `//`?

**Comment by dorian3343** [comment]
Ive been thinking a lot about how automatic documentation should work and how we could implement it, this all started because of #620 (which I think we should implement as the basis for the documentation website)

Heres how it could look

```
/*Description:
  Comp description of what it does etc
/*Authors:
 Authors of component
/*
/*Examples:
 Examples of the comp
/*

// and more


component Foo(start any) (sig any){
  // Component definition
}
```
This should also be plugged into the LSP

**Comment by emil14** [comment]
I don't see a reason why multi-line comments are needed for now
